// Code generated by go-localize; DO NOT EDIT.
// This file was generated by robots at
// 2022-11-18 14:08:41.927049737 +0300 MSK m=+0.000832427

package localizations

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

var localizations = map[string]string{
	"en.messages.added-required-request-body":       "added required request body",
	"en.messages.at":                                "at",
	"en.messages.in":                                "in",
	"en.messages.request-parameter-pattern-added":   "added the pattern '%s' for the %s request parameter %s",
	"en.messages.request-parameter-pattern-changed": "changed the pattern for the %s request parameter %s from '%s' to '%s'",
	"en.messages.request-parameter-removed":         "deleted the %s request parameter %s",
	"en.messages.request-property-pattern-added":    "added the pattern '%s' for the request property %s",
	"en.messages.request-property-pattern-changed":  "changed the pattern for the request property %s from '%s' to '%s'",
	"en.messages.total-errors":                      "Backward compatibility errors (%d):\n",
	"ru.messages.added-required-request-body":       "добавлено обязательное тело запроса",
	"ru.messages.at":                                "в",
	"ru.messages.in":                                "в",
	"ru.messages.request-parameter-pattern-added":   "добавлен pattern '%s' для %s параметра запроса %s",
	"ru.messages.request-parameter-pattern-changed": "изменён pattern для %s параметра запроса %s со значения '%s' на значение '%s'",
	"ru.messages.request-parameter-removed":         "удалён %s параметр запроса %s",
	"ru.messages.request-property-pattern-added":    "добавлен pattern '%s' для поля запроса %s",
	"ru.messages.request-property-pattern-changed":  "изменён pattern для поля запроса %s со значения '%s' на значение '%s'",
	"ru.messages.total-errors":                      "Ошибки обратной совместимости (всего: %d):\n",
}

type Replacements map[string]interface{}

type Localizer struct {
	Locale         string
	FallbackLocale string
	Localizations  map[string]string
}

func New(locale string, fallbackLocale string) *Localizer {
	t := &Localizer{Locale: locale, FallbackLocale: fallbackLocale}
	t.Localizations = localizations
	return t
}

func (t Localizer) SetLocales(locale, fallback string) Localizer {
	t.Locale = locale
	t.FallbackLocale = fallback
	return t
}

func (t Localizer) SetLocale(locale string) Localizer {
	t.Locale = locale
	return t
}

func (t Localizer) SetFallbackLocale(fallback string) Localizer {
	t.FallbackLocale = fallback
	return t
}

func (t Localizer) GetWithLocale(locale, key string, replacements ...*Replacements) string {
	str, ok := t.Localizations[t.getLocalizationKey(locale, key)]
	if !ok {
		str, ok = t.Localizations[t.getLocalizationKey(t.FallbackLocale, key)]
		if !ok {
			return key
		}
	}

	// If the str doesn't have any substitutions, no need to
	// template.Execute.
	if strings.Index(str, "}}") == -1 {
		return str
	}

	return t.replace(str, replacements...)
}

func (t Localizer) Get(key string, replacements ...*Replacements) string {
	str := t.GetWithLocale(t.Locale, key, replacements...)
	return str
}

func (t Localizer) getLocalizationKey(locale string, key string) string {
	return fmt.Sprintf("%v.%v", locale, key)
}

func (t Localizer) replace(str string, replacements ...*Replacements) string {
	b := &bytes.Buffer{}
	tmpl, err := template.New("").Parse(str)
	if err != nil {
		return str
	}

	replacementsMerge := Replacements{}
	for _, replacement := range replacements {
		for k, v := range *replacement {
			replacementsMerge[k] = v
		}
	}

	err = template.Must(tmpl, err).Execute(b, replacementsMerge)
	if err != nil {
		return str
	}
	buff := b.String()
	return buff
}
