name: detect-broken-links
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  check-links:
    name: check-links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: '.github/workflows/mlc_config.json'